l=["Kasia","Basia","Marek","Darek"]
l.append("Józek")
l.extend(["Ania","Basia"])
print(l)
l = sorted(l)
print(l)
print(l[3])
print(l[:2])
print(l[-2:])
l.remove("Basia")
l.remove("Basia")
print(l)
print(len(l))
l=tuple(l)
print(l)